### ISSUE TITLE
Error compiling Mumble OSX

### ISSUE THREAD

**Issue by evangelist88** [mumble-voip/mumble#2309]
I made this step to build mumble:
- $ git clone https://github.com/mumble-voip/mumble-releng
- I create the folder MumbleBuild -> mkdir ~/MumbleBuild
- $ cd mumble-releng/buildenv/1.3.x/osx 
- $ ./setup.command
- $ source /MumbleBuild/osx-1.3.x-2014-05-294bfbe10/env
- $ cd ${MUMBLE_PREFIX}/mumble-releng
- $ ./build-all.bash

I built all

Then I have tried to compile mumble doing:
- $ git clone --recursive https://github.com/mumble-voip/mumble 
- $ cd mumble
- $ qmake -recursive main.pro CONFIG+='release static opus no-server no-dbus no-ice'
- $ make

This is my folder:
![cattura](https://cloud.githubusercontent.com/assets/11414816/15579671/f8181820-2365-11e6-96dc-a14c28411765.PNG)

At the end I have this error:
**./Mumble.pb.h:9:19: fatal error: 'google/protobuf/stubs/common.h' file not found**

![cattura](https://cloud.githubusercontent.com/assets/11414816/15579719/1b6b08b4-2366-11e6-8415-937b3ac8f030.PNG)

Could anyone help me?!

Thanks a lot

**Comment by mkrautz** [comment]
You need to `source /MumbleBuild/osx-1.3.x-2014-05-294bfbe10/env` before you run qmake.

I can't, from your description, see if you built the environment in a separate terminal, or you did it in the same one.

So, make sure you do `source /MumbleBuild/osx-1.3.x-2014-05-294bfbe10/env` before building...

**Comment by mkrautz** [comment]
Sorry. If you can use qmake, you should be in the env. I'll have a closer look...

**Comment by evangelist88** [comment]
When I use qmake I'm inside the mumble folder... I don't understand the hint...

**Comment by mkrautz** [comment]
Yeah -- what I wanted to say above is that my previous comment was wrong.

 Now...

I think what may be going on here is that we switched protobuf to use pkg-config in the build.
This might have broken the OS X build...

I'll look into it.

**Comment by reelsense** [comment]
This happens to my when I compile on FreeBSD 10.3

**Comment by mkrautz** [comment]
@reelsense Really? We build with Qt 5 on FreeBSD 10.3 in CI, and it works fine. Do you have protobuf installed?

**Comment by reelsense** [comment]
yes
 ``pkg install protobuf
...
The most recent version of packages are already installed``

**Comment by reelsense** [comment]
This is on a fresh jail in iocage.
I did a ``git clone``
installed all the dependencies listed on the wiki:
``pkg install boost-libs ice qt5-core qt5-network qt5-xml qt5-qmake qt5-sqldrivers-sqlite3 protobuf qt5-buildtools``

**Comment by mkrautz** [comment]
@reelsense I believe your issue is that /usr/local/lib/pkgconfig isn't in your PKG_CONFIG_PATH.

The change to use pkg-config for protobuf is fairly recent.

**Comment by mkrautz** [comment]
@evangelist88 

I believe there was an error in your build.

Looking at your screenshot, it seems like $MUMBLE_PREFIX was not set when you invoked `qmake`.
See:

![mumble_prefix](https://cloud.githubusercontent.com/assets/36527/16707580/09a351d2-45d4-11e6-8926-4f1c1edc971e.png)

That line should read `/MumbleBuild/osx-1.3.x-2014-05-294bfbe10/include` (that is, the expanded form of `$MUMBLE_PREFIX/include`. Since it's `/include` in your case, your MUMBLE_PREFIX environment variable must not have been set when invoking qmake.

This should hopefully give you a working build:

    $ source /MumbleBuild/osx-1.3.x-2014-05-294bfbe10/env
    $ cd /path/to/mumble
    $ git clean -dfx -f # clean the build dir
    $ qmake -recursive main.pro CONFIG+='release static opus no-server no-dbus no-ice'
    $ make

**Comment by mkrautz** [comment]
Removed from the 1.3.0 milestone since the build is actually working...

**Comment by mkrautz** [comment]
https://github.com/mumble-voip/mumble/pull/2413 should have fixed most problems like these.
