### ISSUE TITLE
error: no match for ‘operator==’

### ISSUE THREAD

**Issue by MariuszXC** [mumble-voip/mumble#5606]
### Description

Compilation fails with:
```cpp
[ 78%] Building CXX object src/mumble/CMakeFiles/mumble.dir/Markdown.cpp.o
/compile/mumble/mumble-1.4.230.src/src/mumble/Markdown.cpp: In function ‘void Markdown::escapeCharacter(QString&, int&)’:
/compile/mumble/mumble-1.4.230.src/src/mumble/Markdown.cpp:346:29: error: no match for ‘operator==’ (operand types are ‘QString’ and ‘QCharRef’)
  346 |  if (tmp.size() == 1 && tmp == str[offset]) {
      |                         ~~~ ^~ ~~~~~~~~~~~
      |                         |                |
      |                         QString          QCharRef
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /compile/mumble/mumble-1.4.230.src/src/mumble/Markdown.h:9,
                 from /compile/mumble/mumble-1.4.230.src/src/mumble/Markdown.cpp:6:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:631:10: note: candidate: ‘bool QString::operator==(QLatin1String) const’
  631 |     bool operator==(QLatin1String s) const;
      |          ^~~~~~~~
/usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:631:35: note:   no known conversion for argument 1 from ‘QCharRef’ to ‘QLatin1String’
  631 |     bool operator==(QLatin1String s) const;
      |                     ~~~~~~~~~~~~~~^
```

### Steps to reproduce

1. unpack mumble-1.4.230.tar.gz
2. cd to mumble-1.4.230.src
3. mkdir build; cd build
4. cmake ..
5. make

### Mumble version

1.4.230

### Mumble component

Both

### OS

Linux

### Reproducible?

Yes

### Additional information

<details>
<summary></summary>

```
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_MBIG_OBJ
-- Performing Test COMPILER_HAS_MBIG_OBJ - Failed
-- ##################################################
-- Mumble version:          1.4.0
-- Architecture:            x64
-- Build type:              Release
-- ##################################################
-- Qt5 component found: Core | Version: 5.5.1
-- Qt5 component found: Network | Version: 5.5.1
-- Qt5 component found: Xml | Version: 5.5.1
-- OpenSSL component found: Crypto | Version: 1.1.1
-- OpenSSL component found: SSL | Version: 1.1.1
-- Protobuf found | Version: 3.12.4
-- Qt5 component found: Concurrent | Version: 5.5.1
-- Qt5 component found: Sql | Version: 5.5.1
-- Qt5 component found: Svg | Version: 5.5.1
-- Qt5 component found: Widgets | Version: 5.5.1
-- Poco component not found: Zip
-- Regular Poco search failed - looking for Poco include dir manually...
-- Found Poco include dir at "/usr/include"
-- Found Poco Zip library at "/usr/lib/libPocoZip.so"
-- sndfile found | Version: 1.0.25
-- X11 component found: Xext
-- X11 component found: Xi
-- Found Git: /usr/bin/git (found version "2.35.1") 
CMake Warning at 3rdparty/opus/cmake/OpusPackageVersion.cmake:61 (message):
  Could not get package version.
Call Stack (most recent call first):
  3rdparty/opus/CMakeLists.txt:5 (get_package_version)


-- Opus project version: 0
-- Looking for floor in m
-- Looking for floor in m - found
-- Performing Test VLA_SUPPORTED
-- Performing Test VLA_SUPPORTED -- success
-- Looking for alloca.h
-- Looking for alloca.h - found
-- Looking for alloca
-- Looking for alloca - found
-- Looking for lrintf
-- Looking for lrintf - not found
-- Looking for lrint
-- Looking for lrint - not found
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Check SIMD support by compiler
-- Looking for xmmintrin.h
-- Looking for xmmintrin.h - found
-- Performing Test SSE1_SUPPORTED
-- Performing Test SSE1_SUPPORTED - Success
-- Looking for emmintrin.h
-- Looking for emmintrin.h - found
-- Performing Test SSE2_SUPPORTED
-- Performing Test SSE2_SUPPORTED - Success
-- Looking for smmintrin.h
-- Looking for smmintrin.h - found
-- Performing Test SSE4_1_SUPPORTED
-- Performing Test SSE4_1_SUPPORTED - Success
-- Looking for immintrin.h
-- Looking for immintrin.h - found
-- Performing Test AVX_SUPPORTED
-- Performing Test AVX_SUPPORTED - Success
-- Performing Test FAST_MATH_SUPPORTED
-- Performing Test FAST_MATH_SUPPORTED - Success
-- Performing Test STACK_PROTECTOR_SUPPORTED
-- Performing Test STACK_PROTECTOR_SUPPORTED - Success
-- Performing Test HIDDEN_VISIBILITY_SUPPORTED
-- Performing Test HIDDEN_VISIBILITY_SUPPORTED - Success
-- Performing Test Wall_SUPPORTED
-- Performing Test Wall_SUPPORTED - Success
-- Performing Test W_SUPPORTED
-- Performing Test W_SUPPORTED - Success
-- Performing Test Wstrictprototypes_SUPPORTED
-- Performing Test Wstrictprototypes_SUPPORTED - Success
-- Performing Test Wextra_SUPPORTED
-- Performing Test Wextra_SUPPORTED - Success
-- Performing Test Wcastalign_SUPPORTED
-- Performing Test Wcastalign_SUPPORTED - Success
-- Performing Test Wnestedexterns_SUPPORTED
-- Performing Test Wnestedexterns_SUPPORTED - Success
-- Performing Test Wshadow_SUPPORTED
-- Performing Test Wshadow_SUPPORTED - Success
-- The following features have been enabled:

 * OPUS_BUILD_SHARED_LIBRARY, build shared library.
 * OPUS_ENABLE_FLOAT_API, compile with the floating point API (for machines with float library).
 * OPUS_HARDENING, run-time checks that are cheap and safe for use in production.
 * OPUS_INSTALL_PKG_CONFIG_MODULE, install pkg-config module.
 * OPUS_INSTALL_CMAKE_CONFIG_MODULE, install CMake package config module.
 * OPUS_VAR_ARRAYS, use variable length arrays for stack arrays.
 * OPUS_STACK_PROTECTOR, use stack protection.
 * OPUS_FORTIFY_SOURCE, add protection against buffer overflows.
 * OPUS_X86_MAY_HAVE_SSE, does runtime check for SSE1 support.
 * OPUS_X86_MAY_HAVE_SSE2, does runtime check for SSE2 support.
 * OPUS_X86_MAY_HAVE_SSE4_1, does runtime check for SSE4.1 support.
 * OPUS_X86_MAY_HAVE_AVX, does runtime check for AVX support.
 * OPUS_X86_PRESUME_SSE, assume target CPU has SSE1 support (override runtime check).
 * OPUS_X86_PRESUME_SSE2, assume target CPU has SSE2 support (override runtime check).

-- The following OPTIONAL packages have been found:

 * Git

-- The following features have been disabled:

 * OPUS_BUILD_TESTING, build tests.
 * OPUS_CUSTOM_MODES, enable non-Opus modes, e.g. 44.1 kHz & 2^n frames.
 * OPUS_BUILD_PROGRAMS, build programs.
 * OPUS_DISABLE_INTRINSICS, disable all intrinsics optimizations.
 * OPUS_FIXED_POINT, compile as fixed-point (for machines without a fast enough FPU).
 * OPUS_FLOAT_APPROX, enable floating point approximations (Ensure your platform supports IEEE 754 before enabling).
 * OPUS_ASSERTIONS, additional software error checking.
 * OPUS_FUZZING, causes the encoder to make random decisions (do not use in production).
 * OPUS_CHECK_ASM, enable bit-exactness checks between optimized and c implementations.
 * OPUS_FIXED_POINT_DEBUG, debug fixed-point implementation.
 * OPUS_USE_ALLOCA, use alloca for stack arrays (on non-C99 compilers).
 * OPUS_NONTHREADSAFE_PSEUDOSTACK, use a non threadsafe pseudostack when neither variable length arrays or alloca is supported.
 * OPUS_FAST_MATH, enable fast math (unsupported and discouraged use, as code is not well tested with this build option).
 * OPUS_X86_PRESUME_SSE4_1, assume target CPU has SSE4.1 support (override runtime check).
 * OPUS_X86_PRESUME_AVX, assume target CPU has AVX support (override runtime check).

-- Disabling warnings for targets: opus
INSTALL TARGETS - target opus has PUBLIC_HEADER files but no PUBLIC_HEADER DESTINATION.
-- Disabling warnings for targets: celt
-- Disabling warnings for targets: speex
-- Disabling warnings for targets: rnnoise
-- speech-dispatcher found | Version: 0.8.3
-- Qt5 component found: DBus | Version: 5.5.1
-- Qt5 component found: LinguistTools | Version: 5.5.1
-- ALSA found
-- Qt5 component found: Sql | Version: 5.5.1
-- File: /compile/mumble/build/src/murmur/murmur_autogen
-- Qt5 component found: DBus | Version: 5.5.1
-- Ice component found: Ice | Version: 3.5.1
-- Ice component found: IceSSL | Version: 3.5.1
-- Ice optional component found: IceUtil | Version: 3.5.1
-- Looking for sys/cdefs.h
-- Looking for sys/cdefs.h - found
-- 
If the 32 bit overlay library fails to compile, make sure the requirements are installed ("g++-multilib" package on Debian-based distributions).

-- Configuring done
-- Generating done
-- Build files have been written to: /compile/mumble/build
```
</details>

**Comment by Krzmbrzl** [comment]
What distro are you using? Qt 5.5 is very old at this point, so it might just be too old to work with Mumble :thinking:

**Comment by MariuszXC** [comment]
Ubuntu 16.04 LTS.
I understand it is old, but for various reasons upgrade is not possible for now.
Anyway, since cmake detection and configuration step did not complain I thought it would compile just fine.

**Comment by Krzmbrzl** [comment]
Yeah 16.04 is not officially supported anymore.

However, if that is the only error you are seeing, you could try to manually patch the offending line
https://github.com/mumble-voip/mumble/blob/74faaba32ea94f9654d461e5e544cf0d7ad36dd8/src/mumble/Markdown.cpp#L347
to either
```cpp
if (tmp.size() == 1 && tmp[0] == str[offset]) {
```
or
```cpp
if (tmp.size() == 1 && tmp == str.at(offset)) {
```

Maybe that is enough to make the error go away :eyes:

**Comment by MariuszXC** [comment]
Thank you. 
tmp[0] == ... did the trick and compilation progressed.
Next point of contention is related to class Poco::XML:Element.

[ 81%] Building CXX object src/mumble/CMakeFiles/mumble.dir/PluginManifest.cpp.o
/compile/mumble/mumble-1.4.230.src/src/mumble/PluginManifest.cpp: In member function ‘void PluginManifest::parse(std::istream&)’:
/compile/mumble/mumble-1.4.230.src/src/mumble/PluginManifest.cpp:29:17: error: invalid use of incomplete type ‘class Poco::XML::Element’
   29 |  if (rootElement->nodeName() != "bundle") {
      |                 ^~
In file included from /usr/include/Poco/DOM/AbstractContainerNode.h:44,
                 from /usr/include/Poco/DOM/Document.h:44,
                 from /compile/mumble/mumble-1.4.230.src/src/mumble/PluginManifest.cpp:11:
/usr/include/Poco/DOM/AbstractNode.h:134:15: note: forward declaration of ‘class Poco::XML::Element’

**Comment by Krzmbrzl** [comment]
Ah now that is indeed an issue in our code-base atm - there's a missing include. Please add a `#include <Poco/DOM/Element.h>` to the other includes at the top of the file and let me know, whether that fixes the issue.

(I will wait with creating a PR that addresses these issues upstream until we have made your build succeed)

**Comment by MariuszXC** [comment]
Before I noted your reply I assumed an older Poco (and in a non standard location, as reported by CMake search output) could be the cause, so I cloned, built and installed Poco from pocoproject git repo. Then made a clean cmake .. && make mumble and progressed further. 
Nevertheless after noticing your reply I also added the missing #include and rerun make. 

Now the compilation stops with:

**Comment by Krzmbrzl** [comment]
This should be fixed by a `#include <stdint>` at the top of `src/mumble/QtWidgetUtils.cpp`

**Comment by MariuszXC** [comment]
<stdint> did not work, however <stdint.h> worked :+1: 

```
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~16.04) 9.4.0
```
Don't think there is anything special about this compiler?

Anyway, now progress stops at:

```
[ 61%] Building CXX object src/mumble/CMakeFiles/mumble.dir/SearchDialog.cpp.o
/compile/mumble/mumble-1.4.230.src/src/mumble/SearchDialog.cpp: In member function ‘virtual void Search::SearchDialog::keyPressEvent(QKeyEvent*)’:
/compile/mumble/mumble-1.4.230.src/src/mumble/SearchDialog.cpp:492:35: error: ‘Cancel’ is not a member of ‘QKeySequence’
  492 |  if (event->matches(QKeySequence::Cancel)) {
      |                                   ^~~~~~
```

**Comment by Krzmbrzl** [comment]
Ah yeah - the C++ header is called `cstdint` not `stdint` :facepalm: 

> Don't think there is anything special about this compiler?

Don't think so either, but it is catching a lot of interesting bugs ^^

> Anyway, now progress stops at:

Might be fixed with adding `#include <QKeySequence>` to the top of `src/mumble/SearchDialog.cpp` :eyes:

**Comment by MariuszXC** [comment]
Did not help :(
```
[ 60%] Building CXX object src/mumble/CMakeFiles/mumble.dir/SearchDialog.cpp.o
/compile/mumble/mumble-1.4.230.src/src/mumble/SearchDialog.cpp: In member function ‘virtual void Search::SearchDialog::keyPressEvent(QKeyEvent*)’:
/compile/mumble/mumble-1.4.230.src/src/mumble/SearchDialog.cpp:493:35: error: ‘Cancel’ is not a member of ‘QKeySequence’
  493 |  if (event->matches(QKeySequence::Cancel)) {
      |                                   ^~~~~~
```

**Comment by Krzmbrzl** [comment]
Turns out that this key is only available since Qt 5.6, even though none of that is mentioned in the docs.
Source: https://github.com/qt/qtbase/commit/126c2cb8fbb50848a5006fd25e83b8afc7b3e781

You could just comment out (or remove) the entire block for now:
https://github.com/mumble-voip/mumble/blob/74faaba32ea94f9654d461e5e544cf0d7ad36dd8/src/mumble/SearchDialog.cpp#L492-L496
If we don't run into more such cases, I could probably get it to work with pre 5.6 as well :eyes:

**Comment by MariuszXC** [comment]
```[ 77%] Linking CXX executable ../../mumble
[100%] Built target mumble
```
:-)

**Comment by Krzmbrzl** [comment]
Sweet! :+1: 
Then I'll now go ahead and create a PR with the respective fixes and changes.

**Comment by Krzmbrzl** [comment]
No, no - I still intend to look into the plugin install issue

**Comment by Krzmbrzl** [comment]
Okay, I am officially unable to reproduce the plugin install issue that you encountered. I tried with current master and with the 1.4.x branch but in either scenario, the plugin installed as expected.
So unless someone finds a way to trigger this reasonably reliably, I think there's not much that I can do about it :eyes:
