### ISSUE TITLE
Compile failure with qt-5.15

### ISSUE THREAD

**Issue by fedeliallalinea** [mumble-voip/mumble#4230]
mumble-1.3.1_rc1 fails to compile with 5.15 returning error:
```
../../release/.moc/mumble/../../../src/mumble/OverlayText.h:42:16: error: field ‘qpp’ has incomplete type ‘QPainterPath’
   42 |   QPainterPath qpp;
      |                ^~~
```
I also reported bug on gentoo bug tracker with a patch to solve issue https://bugs.gentoo.org/726692

**Desktop (please complete the following information):**
 - OS: gentoo linux
 - Version: mumble-1.3.1_rc1

**Comment by davidebeatrici** [comment]
Thank you very much for your contribution!
