### ISSUE TITLE
latest release 1.3.1-rc1 fails to build

### ISSUE THREAD

**Issue by david-geiger** [mumble-voip/mumble#4065]
Hi,

I tried On Mageia Cauldron to build latest 1.3.1-rc1 release but it fails to build from source due to missing headers:

> -I../../src -I. -I../mumble_proto -I../../3rdparty/arc4random-src -Imurmur_ice -Imurmur_grpc -I../../3rdparty/qqbonjour-src -isystem /usr/include/avahi-compat-libdns_sd -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I../../release/.moc/murmur -I/usr/lib64/qt5/mkspecs/linux-g++ -o ../../release/.obj/murmur/MurmurGRPCImpl.o MurmurGRPCImpl.cpp
MurmurGRPCImpl.cpp:21:10: fatal error: Utils.h: No such file or directory
   21 | #include "Utils.h"
      |          ^~~~~~~~~
compilation terminated.

[build.0.20200413083309.log](https://github.com/mumble-voip/mumble/files/4470008/build.0.20200413083309.log)

Regards,
David

**Comment by davidebeatrici** [comment]
Hi,

Is `src/Utils.h` present?

**Comment by Krzmbrzl** [comment]
Were you able to build successfully with GRPC enabled for the 1.3.0 branch?

**Comment by david-geiger** [comment]
Nop src/Utils.h is not present.

And 1.3.0 release build sucessfully:

[build.0.20200319152711.log](https://github.com/mumble-voip/mumble/files/4471450/build.0.20200319152711.log)

**Comment by davidebeatrici** [comment]
Thank you for reporting the issue, 58d27c68a9d131e111ca488b42469bdae68e06e2 should be backported.

**Comment by Krzmbrzl** [comment]
@davidebeatrici will you do the backport? Do we want to backport #3644 as a whole or only that single commit?

**Comment by davidebeatrici** [comment]
Single commit, feel free to do it.

**Comment by david-geiger** [comment]
Now another build issue:

> ../Group.cpp:6:10: fatal error: murmur_pch.h: No such file or directory
 #include "murmur_pch.h"
          ^~~~~~~~~~~~~~
compilation terminated.

I think that this commit will also be needed: https://github.com/mumble-voip/mumble/commit/5a07244a449592a143a628fde9b84846ee82e0


[mumble_build_log.txt](https://github.com/mumble-voip/mumble/files/4475494/mumble_build_log.txt)

**Comment by david-geiger** [comment]
So now after PR https://github.com/mumble-voip/mumble/pull/4068/commits/d68beacfd9d65fe012b9a90eeeb6fe4027343cda again a build issue:

> AudioConfigDialog.cpp: In member function 'virtual void AudioInputDialog::load(const Settings&)':
AudioConfigDialog.cpp:120:28: error: 'iroundf' was not declared in this scope

Seems now this commit https://github.com/mumble-voip/mumble/commit/15831dbca85dd906edbad2bfff2b147527a456e2 is needed.

**Comment by david-geiger** [comment]
So ok now it build fine with PR https://github.com/mumble-voip/mumble/pull/4068

**Comment by Krzmbrzl** [comment]
Huh? how can that be? I've rolled back to backporting only that first commit as the other commits introduced loads of problems with Qt4 xD
Have you built with Qt5 and from an older version (aka 12 hours ago or so) of that PR?

**Comment by david-geiger** [comment]
Yes I've compiled with Qt5 and with the PR from yersterday.

**Comment by Krzmbrzl** [comment]
Ah okay that explains it ^^
I'm at fixing up the PR right now. Would appreciate if you could find the time to verify it to be working afterwards (I'll probably push the fixes within the next hour or so) :)

**Comment by david-geiger** [comment]
Yes I can no problem, but which commit/PR should I use exactly?

**Comment by Krzmbrzl** [comment]
#4068 there's only a single commit in it, but it's not the same that was in it yesterday ^^

**Comment by david-geiger** [comment]
Here it built fine with this single commit against Qt5.

**Comment by Krzmbrzl** [comment]
Perfect, thanks :)

**Comment by Krzmbrzl** [comment]
Fixed by #4068

**Comment by theAkito** [comment]
@Krzmbrzl 

Trying to build tag 1.3.1-rc1 results in:
```
MurmurGRPCImpl.cpp:21:10: fatal error: Utils.h: No such file or directory
   21 | #include "Utils.h"
      |          ^~~~~~~~~
compilation terminated.
make[2]: *** [Makefile.Release:1139: ../../release/.obj/murmur/MurmurGRPCImpl.o] Error 1
make[2]: Leaving directory '/root/mumble/src/murmur'
make[1]: *** [Makefile:42: release] Error 2
make[1]: Leaving directory '/root/mumble/src/murmur'
make: *** [Makefile:460: sub-src-murmur-release_ordered] Error 2
```

**Comment by Krzmbrzl** [comment]
Yeah I think that's just how GitHub tags work...

From your comment I take it that the build works with the 1.3.x branch for you, right?

**Comment by theAkito** [comment]
@Krzmbrzl 
At the time of commenting, I had not tried it, yet.

However, now I can confirm the `1.3.x` branch indeed works, as it contains all the backported commits, too.

As for the tags, one would need to delete the respective local and remote tag, then re-push the newly created tag that contains all the new backported commits.

**Comment by Krzmbrzl** [comment]
Yeah we should release 1.3.1 soon anyways. Thus I don't think it to be that bad if the 1.3.1.rc1 has some issues...
