### ISSUE TITLE
Building on macOS 12/m1 breaks

### ISSUE THREAD

**Issue by thegcat** [mumble-voip/mumble#5636]
### Description

It is currently not possible to build the mumble client on macOS.

### Steps to reproduce

```
cd build
cmake -Dice=off -DCMAKE_BUILD_TYPE=Release ..
cmake --build . -j 4
```

### Mumble version

3960373d9

### Mumble component

Client

### OS

macOS

### Reproducible?

Yes

### Relevant log output

```shell
[ 65%] Building CXX object src/mumble/CMakeFiles/mumble.dir/PAAudio.cpp.o
/Users/thegcat/Code/m1/mumble/src/mumble/GlobalShortcut_macx.mm:26:7: error: variable 'forward' set but not used [-Werror,-Wunused-but-set-variable]
        bool forward = false;
             ^
1 error generated.
make[2]: *** [src/mumble/CMakeFiles/mumble.dir/GlobalShortcut_macx.mm.o] Error 1
```

**Comment by thegcat** [comment]
This probably is caused by c4a2930dc3 which punts the only time `forward` is used behind an `ifdef`.

**Comment by Krzmbrzl** [comment]
Please try `cmake -Dwarnings-as-errors=OFF` to see if you are able to build Mumble with this option

**Comment by thegcat** [comment]
I had just put a dummy `if (forward) { }`, but `-Dwarnings-as-errors=OFF` works too.

**Comment by thegcat** [comment]
I also tried 33ccf4177ad021b17f09ba584fff0f6d330da4c2, works a charm, thanks!

**Comment by Krzmbrzl** [comment]
Perfect - thanks for letting me know :+1:
